### ISSUE TITLE
Get most current agency org charts (as of their last realignment)

### ISSUE THREAD

**Issue by emanuelfeld** [DCgov/organizational-chart#1]

**Comment by katmeresin** [comment]
Let me know how I can help with this one. For example, can we do a download of names/titles from the listing of salaries that DCHR puts out?

My understanding is that many agencies have not actually created/maintained these, but it may be that DCHR has the closest option in people soft given who signs timesheets.

**Comment by katmeresin** [comment]
Separately, is there a preferred format if these are not compiled? I might make a new one for DSLBD, thus I could input it into any tool/format as a best practice.

**Comment by emanuelfeld** [comment]
Agencies are required to submit an organizational chart to DCHR whenever they undergo a "realignment". There are some changes they may make that do not entail a realignment, but they're seemingly minor ones. I've tried, but have been unable so far to get the most recent realignment charts for all agencies. From what I learned, they are not being produced by People Soft. They make them either in PDF format or using powerpoint using an unknown process. 

There seems to be some idealized structure for agencies (which I don't believe any truly conforms to) of:

agency > administration > office > division > branch > section > unit

You can see in the files directory of this repo what the agencies have been putting out (unclear if these are the same as they're sending DCHR).

I attempted to create some sort of parseable org chart based on the mayor's org chart PDF and the budget in chart.yaml, with entries like:

```
  - name: Commission on the Arts and Humanities
    abbreviation: DCCAH
    code: BX0
    homepage: http://dcarts.dc.gov/
    branch: Executive
    parent: Office of the Deputy Mayor for Planning and Economic Development
    social:
      - type: twitter
        url: https://twitter.com/TheDCArts
      - type: facebook
        url: https://www.facebook.com/TheDCArts/
```

That seems to me a fairly reasonable format (perhaps with an added attribute giving the type of thing, e.g. agency, division, program, or whatever). It's hard to make anything more structured if the agencies don't share one.

I don't think we'd want to go down to the level of individual employees, which will change pretty frequently. 

But, this is all to say, that there is no specific tool, format, etc. that has been agreed upon, so feel free to take a stab at DSLB's chart. So long as it's in something text-like (e.g. YAML, JSON) it's pretty easy to switch things around.
